# Project-wide Gradle settings

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

reactNativeArchitectures=x86,x86_64

# ❌ Disable New Architecture (Turbo / Nitro)
newArchEnabled=false

# ❌ Disable Hermes (CRITICAL)
hermesEnabled=false

# ❌ Disable NitroModules explicitly
nitro.enabled=false
